apiVersion: v2
name: task-management
description: A Helm chart for Task Management Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - task-management
  - productivity
  - collaboration
  - ai
home: https://github.com/your-org/task-management-app
sources:
  - https://github.com/your-org/task-management-app
maintainers:
  - name: Platform Team
    email: platform@company.com