# 🔒 POD DISRUPTION BUDGETS (PDB)
# Ensure high availability during cluster maintenance for ecommerce-app

---
# Pod Disruption Budget for Backend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ecommerce-backend-pdb
  namespace: ecommerce-production
  labels:
    app: ecommerce-backend
    tier: production
    component: reliability
spec:
  selector:
    matchLabels:
      app: ecommerce-backend
  minAvailable: 2
  maxUnavailable: 1

---
# Pod Disruption Budget for Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ecommerce-frontend-pdb
  namespace: ecommerce-production
  labels:
    app: ecommerce-frontend
    tier: production
    component: reliability
spec:
  selector:
    matchLabels:
      app: ecommerce-frontend
  minAvailable: 1
  maxUnavailable: 50%

---
# Pod Disruption Budget for Database
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ecommerce-database-pdb
  namespace: ecommerce-production
  labels:
    app: database
    tier: production
    component: reliability
spec:
  selector:
    matchLabels:
      app: database
  minAvailable: 1
  maxUnavailable: 0
