# E-commerce Platform Configuration
# This stores application configuration and secrets

apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # Database configuration
  DB_HOST: "mongodb-service"
  DB_PORT: "27017"
  DB_NAME: "ecommerce"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Application configuration
  NODE_ENV: "production"
  PORT: "5000"
  
  # Payment gateway configuration (non-sensitive)
  PAYMENT_GATEWAY_URL: "https://api.stripe.com"
  
  # Email service configuration
  EMAIL_SERVICE: "sendgrid"
  
---
# Secrets for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USERNAME: bW9uZ29fdXNlcg==  # mongo_user
  DB_PASSWORD: bW9uZ29fcGFzc3dvcmQ=  # mongo_password
  
  # JWT secrets
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXk=  # super_secret_jwt_key
  JWT_REFRESH_SECRET: cmVmcmVzaF9zZWNyZXRfa2V5  # refresh_secret_key
  
  # Payment gateway secrets
  STRIPE_SECRET_KEY: c2tfdGVzdF8xMjM0NTY3ODkw  # sk_test_1234567890
  STRIPE_WEBHOOK_SECRET: d2hfc2VjXzEyMzQ1Njc4OTA=  # wh_sec_1234567890
  
  # Email service secrets
  SENDGRID_API_KEY: U0cuMTIzNDU2Nzg5MA==  # SG.1234567890
  
  # Redis password
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=  # redis_password
