version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://taskuser:taskpass@db:5432/taskmanagement?sslmode=disable
      - PORT=8080
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - task-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - task-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=taskmanagement
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge
