apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
  namespace: ecommerce-lab
  labels:
    app.kubernetes.io/name: ecommerce-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ecommerce-backend
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ecommerce-backend
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: ecommerce
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: temitayocharles/ecommerce-backend:latest
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 300m
              memory: 256Mi
              ephemeral-storage: 300Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
  namespace: ecommerce-lab
  labels:
    app.kubernetes.io/name: ecommerce-backend
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: ecommerce-backend
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
