apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-lab
  labels:
    app.kubernetes.io/name: ecommerce
    app.kubernetes.io/component: config
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: ecommerce
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  NODE_ENV: development
  API_BASE_URL: http://ecommerce-backend:5000
