apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-service-account
  namespace: weather
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weather-role
  namespace: weather
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weather-role-binding
  namespace: weather
subjects:
- kind: ServiceAccount
  name: weather-service-account
  namespace: weather
roleRef:
  kind: Role
  name: weather-role
  apiGroup: rbac.authorization.k8s.io
