apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: educational-platform
  labels:
    app: backend
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app: backend
  minAvailable: 2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: educational-platform
  labels:
    app: frontend
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  minAvailable: 2
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: educational-platform-quota
  namespace: educational-platform
  labels:
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: resource-management
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: educational-platform-limits
  namespace: educational-platform
  labels:
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: resource-management
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "2"
      memory: "2Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
  - type: PersistentVolumeClaim
    max:
      storage: "100Gi"
    min:
      storage: "1Gi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: educational-platform-sa
  namespace: educational-platform
  labels:
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: security
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: educational-platform-role
  namespace: educational-platform
  labels:
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: security
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: educational-platform-binding
  namespace: educational-platform
  labels:
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: security
subjects:
- kind: ServiceAccount
  name: educational-platform-sa
  namespace: educational-platform
roleRef:
  kind: Role
  name: educational-platform-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: educational-platform
  labels:
    app.kubernetes.io/name: educational-platform
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "rules.yml"
    
    scrape_configs:
      - job_name: 'educational-platform-backend'
        static_configs:
          - targets: ['backend-service:8080']
        metrics_path: '/actuator/prometheus'
        scrape_interval: 10s
        
      - job_name: 'educational-platform-postgres'
        static_configs:
          - targets: ['postgres-service:5432']
        scrape_interval: 30s
        
      - job_name: 'educational-platform-redis'
        static_configs:
          - targets: ['redis-service:6379']
        scrape_interval: 30s
        
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - educational-platform
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
  
  rules.yml: |
    groups:
      - name: educational-platform-alerts
        rules:
          - alert: HighCPUUsage
            expr: container_cpu_usage_rate{namespace="educational-platform"} > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 80% for more than 5 minutes"
          
          - alert: HighMemoryUsage
            expr: container_memory_usage_bytes{namespace="educational-platform"} / container_spec_memory_limit_bytes > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Memory usage is above 90% for more than 5 minutes"
          
          - alert: PodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total{namespace="educational-platform"}[5m]) > 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Pod is crash looping"
              description: "Pod {{ $labels.pod }} is restarting frequently"
          
          - alert: DatabaseDown
            expr: up{job="educational-platform-postgres"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "PostgreSQL database is down"
              description: "PostgreSQL database has been down for more than 1 minute"
          
          - alert: RedisDown
            expr: up{job="educational-platform-redis"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Redis cache is down"
              description: "Redis cache has been down for more than 1 minute"
