# 🔒 POD DISRUPTION BUDGETS (PDB)
# Ensure high availability during cluster maintenance for social-media-platform

---
# Pod Disruption Budget for Backend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: social-backend-pdb
  namespace: social-production
  labels:
    app: social-backend
    tier: production
    component: reliability
spec:
  selector:
    matchLabels:
      app: social-backend
  minAvailable: 2
  maxUnavailable: 1

---
# Pod Disruption Budget for Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: social-frontend-pdb
  namespace: social-production
  labels:
    app: social-frontend
    tier: production
    component: reliability
spec:
  selector:
    matchLabels:
      app: social-frontend
  minAvailable: 1
  maxUnavailable: 50%

---
# Pod Disruption Budget for Database
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: social-database-pdb
  namespace: social-production
  labels:
    app: database
    tier: production
    component: reliability
spec:
  selector:
    matchLabels:
      app: database
  minAvailable: 1
  maxUnavailable: 0
