apiVersion: v1
kind: ServiceAccount
metadata:
  name: social-media-backend-sa
  namespace: social-media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: social-media
  name: social-media-backend-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: social-media-backend-rolebinding
  namespace: social-media
subjects:
- kind: ServiceAccount
  name: social-media-backend-sa
  namespace: social-media
roleRef:
  kind: Role
  name: social-media-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: social-media-frontend-sa
  namespace: social-media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: social-media
  name: social-media-frontend-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: social-media-frontend-rolebinding
  namespace: social-media
subjects:
- kind: ServiceAccount
  name: social-media-frontend-sa
  namespace: social-media
roleRef:
  kind: Role
  name: social-media-frontend-role
  apiGroup: rbac.authorization.k8s.io
