apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: educational-backend-pdb
  namespace: educational
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: educational-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: educational-frontend-pdb
  namespace: educational
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: educational-frontend
