apiVersion: v1
kind: ServiceAccount
metadata:
  name: educational-backend-sa
  namespace: educational
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: educational-backend-role
  namespace: educational
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: educational-backend-rolebinding
  namespace: educational
subjects:
- kind: ServiceAccount
  name: educational-backend-sa
  namespace: educational
roleRef:
  kind: Role
  name: educational-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: educational-monitoring-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educational-monitoring-rolebinding
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: educational-monitoring-role
  apiGroup: rbac.authorization.k8s.io
