apiVersion: apps/v1
kind: Deployment
metadata:
  name: educational-backend
  namespace: educational-lab
  labels:
    app.kubernetes.io/name: educational-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: educational
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: educational-backend
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: educational-backend
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: educational
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: temitayocharles/educational-backend:latest
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 300m
              memory: 256Mi
              ephemeral-storage: 300Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: educational-backend
  namespace: educational-lab
  labels:
    app.kubernetes.io/name: educational-backend
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: educational-backend
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
