apiVersion: apps/v1
kind: Deployment
metadata:
  name: educational-frontend
  namespace: educational-lab
  labels:
    app.kubernetes.io/name: educational-frontend
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: educational
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: educational-frontend
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: educational-frontend
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: educational
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: temitayocharles/educational-frontend:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: REACT_APP_API_URL
              value: http://educational-backend:5000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 50Mi
            limits:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: 200Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: educational-frontend
  namespace: educational-lab
  labels:
    app.kubernetes.io/name: educational-frontend
    app.kubernetes.io/component: ui
spec:
  selector:
    app.kubernetes.io/name: educational-frontend
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
