apiVersion: v1
kind: Namespace
metadata:
  name: social-media
  labels:
    app: social-media-platform
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: social-media-config
  namespace: social-media
data:
  RAILS_ENV: "production"
  RACK_ENV: "production"
  CDN_URL: "https://cdn.socialmedia.example.com"
  FROM_EMAIL: "noreply@socialmedia.example.com"
  ALLOWED_HOSTS: "api.socialmedia.example.com,socialmedia.example.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: social-media-secrets
  namespace: social-media
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # echo -n "your-secret" | base64
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYi5leGFtcGxlLmNvbTo1NDMyL3NvY2lhbF9tZWRpYQ==
  redis-url: cmVkaXM6Ly9yZWRpcy5leGFtcGxlLmNvbTo2Mzc5
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWhlcmU=
  rails-master-key: eW91ci1yYWlscy1tYXN0ZXIta2V5LWhlcmU=
  sendgrid-api-key: U0cueW91ci1zZW5kZ3JpZC1hcGkta2V5LWhlcmU=
  cloudinary-cloud-name: eW91ci1jbG91ZGluYXJ5LWNsb3VkLW5hbWU=
  cloudinary-api-key: eW91ci1jbG91ZGluYXJ5LWFwaS1rZXk=
  cloudinary-api-secret: eW91ci1jbG91ZGluYXJ5LWFwaS1zZWNyZXQ=
  google-client-id: eW91ci1nb29nbGUtY2xpZW50LWlk
  google-client-secret: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==
  facebook-app-id: eW91ci1mYWNlYm9vay1hcHAtaWQ=
  facebook-app-secret: eW91ci1mYWNlYm9vay1hcHAtc2VjcmV0
