apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-backend
  namespace: social-media
  labels:
    app: social-media-backend
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: social-media-backend
      tier: api
  template:
    metadata:
      labels:
        app: social-media-backend
        tier: api
    spec:
      containers:
      - name: backend
        image: social-media-backend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: social-media-config
              key: RAILS_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: jwt-secret
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: rails-master-key
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: sendgrid-api-key
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: cloudinary-cloud-name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: cloudinary-api-key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: cloudinary-api-secret
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-backend-service
  namespace: social-media
  labels:
    app: social-media-backend
spec:
  selector:
    app: social-media-backend
    tier: api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
