apiVersion: v1
kind: Namespace
metadata:
  name: medical-care-system
  labels:
    name: medical-care-system
    compliance: hipaa
    tier: production
    app.kubernetes.io/name: medical-care-system
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: medical-care-quota
  namespace: medical-care-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    pods: "20"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: medical-care-limits
  namespace: medical-care-system
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
