apiVersion: v1
kind: Namespace
metadata:
  name: social-lab
  labels:
    app.kubernetes.io/name: social-lab
    app.kubernetes.io/part-of: lab-06-social-scaling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-database
  namespace: social-lab
  labels:
    app.kubernetes.io/name: social-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: social-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: social-database
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:15.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: social
            - name: POSTGRES_USER
              value: social_user
            - name: POSTGRES_PASSWORD
              value: social_pass
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 200Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: social-database
  namespace: social-lab
spec:
  selector:
    app.kubernetes.io/name: social-database
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-backend
  namespace: social-lab
  labels:
    app.kubernetes.io/name: social-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: social-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: social-backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: temitayocharles/social-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: postgresql://social_user:social_pass@social-database:5432/social
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 300m
              memory: 256Mi
              ephemeral-storage: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: social-backend
  namespace: social-lab
spec:
  selector:
    app.kubernetes.io/name: social-backend
  ports:
    - port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-frontend
  namespace: social-lab
  labels:
    app.kubernetes.io/name: social-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: social-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: social-frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: temitayocharles/social-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 50Mi
            limits:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: social-frontend
  namespace: social-lab
spec:
  selector:
    app.kubernetes.io/name: social-frontend
  ports:
    - port: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: social-backend
  namespace: social-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
