name: Test Docker Hub Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Hub Secrets
        run: |
          echo "Testing Docker Hub connection..."
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "❌ DOCKER_USERNAME secret is not set"
            exit 1
          else
            echo "✅ DOCKER_USERNAME secret is set"
          fi
          
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "❌ DOCKER_PASSWORD secret is not set"
            exit 1
          else
            echo "✅ DOCKER_PASSWORD secret is set"
          fi
          
          echo "🎉 All secrets are configured!"

      - name: Test Docker Hub Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test Docker Hub Access
        run: |
          echo "🔍 Testing Docker Hub access..."
          docker run --rm hello-world
          echo "✅ Docker Hub access successful!"