apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-demo
  namespace: label-lab
  labels:
    app: trace-demo
    lab: fundamentals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trace-demo
  template:
    metadata:
      labels:
        app: trace-demo
        lab: fundamentals
    spec:
      automountServiceAccountToken: false
      containers:
        - name: web
          image: nginx:1.27.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trace-demo
  namespace: label-lab
  labels:
    app: trace-demo
    lab: fundamentals
spec:
  selector:
    app: trace-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
